name: Release Tag Automation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3
      # 2. Node.js 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      # 2. 버전 태그 계산 (package.json 파일에서 버전 정보 추출)
      - name: 버전 정보 추출
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=${VERSION}"
          echo "version=${VERSION}" >> $GITHUB_ENV

      # 3. Release 태그 생성
      - name: Release 태그 생성
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "EN-hyeoninchoi"
          git config --global user.email "hyeonin.choi@enlighten.kr"
          git tag -a "v$VERSION" -m "Release v$VERSION"
          git push origin "v$VERSION"


      # 4. GitHub Release 생성
      - name: GitHub Release 생성
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "Release v${{ env.VERSION }}"
          body: |
            새로운 릴리즈입니다!
            draft: false
            prerelease: false
